import type { LessonContentInput } from '../../src/lessonContent/schema.js';

/** Inglés desde Cero (A1). [módulo][lección], en el mismo orden que el seed. */
export const inglesDesdeCero: LessonContentInput[][] = [
  // ─── Módulo 1: Primeros pasos ───────────────────────────────────────────
  [
    {
      objective: 'Saludar, despedirte y presentarte en inglés con frases simples y naturales.',
      slides: [
        { en: 'Hello! Hi!', es: '¡Hola!', note: '"Hi" es más informal que "Hello".' },
        { en: 'Good morning. Good afternoon. Good evening.', es: 'Buenos días. Buenas tardes. Buenas noches (al llegar).' },
        { en: "My name is Ana. I'm from Colombia.", es: 'Me llamo Ana. Soy de Colombia.' },
        { en: 'Nice to meet you!', es: '¡Mucho gusto!', note: 'Responde: "Nice to meet you too!"' },
        { en: 'Goodbye! See you later!', es: '¡Adiós! ¡Nos vemos!' },
      ],
      vocabulary: [
        { en: 'Hello', es: 'Hola', example: 'Hello, how are you?', emoji: '👋' },
        { en: 'Good morning', es: 'Buenos días', example: 'Good morning, teacher!', emoji: '🌅' },
        { en: 'Good night', es: 'Buenas noches (al despedirte)', example: 'Good night, see you tomorrow.', emoji: '🌙' },
        { en: 'Name', es: 'Nombre', example: 'What is your name?', emoji: '🏷️' },
        { en: 'Nice to meet you', es: 'Mucho gusto', example: 'Hi Carlos, nice to meet you!', emoji: '🤝' },
        { en: 'Goodbye', es: 'Adiós', example: 'Goodbye, have a nice day!', emoji: '👋' },
        { en: 'Thank you', es: 'Gracias', example: 'Thank you very much!', emoji: '🙏' },
      ],
      grammar: {
        title: 'El verbo "to be" para presentarte',
        explanation:
          'Para decir quién eres o de dónde eres usas el verbo "to be" (ser/estar). Con "I" se usa "am", y casi siempre se contrae: "I am" → "I\'m". Para preguntar el nombre: "What\'s your name?" (What is).',
        examples: [
          { en: "I'm Laura.", es: 'Soy Laura.' },
          { en: "I'm from Medellín.", es: 'Soy de Medellín.' },
          { en: "What's your name?", es: '¿Cómo te llamas?' },
          { en: "Where are you from?", es: '¿De dónde eres?' },
        ],
        tip: '"Good night" solo se usa para despedirse. Para saludar en la noche di "Good evening".',
      },
      dialogue: {
        title: 'En la primera clase',
        lines: [
          { speaker: 'Laura', en: "Hi! I'm Laura. What's your name?", es: '¡Hola! Soy Laura. ¿Cómo te llamas?' },
          { speaker: 'Carlos', en: "Hello! My name is Carlos.", es: '¡Hola! Me llamo Carlos.' },
          { speaker: 'Laura', en: 'Nice to meet you, Carlos. Where are you from?', es: 'Mucho gusto, Carlos. ¿De dónde eres?' },
          { speaker: 'Carlos', en: "Nice to meet you too. I'm from Cali.", es: 'Igualmente. Soy de Cali.' },
          { speaker: 'Laura', en: 'Cool! Welcome to the class.', es: '¡Genial! Bienvenido a la clase.' },
        ],
      },
      exercises: [
        { type: 'choice', prompt: 'Son las 8:00 a. m. ¿Cómo saludas?', options: ['Good night', 'Good morning', 'Good evening'], answer: 1, explanation: '"Good morning" se usa hasta el mediodía.' },
        { type: 'fill', sentence: 'Hi, ___ Valentina.', answers: ["I'm", 'I am'], hint: 'Yo soy…' },
        { type: 'order', words: ['Nice', 'to', 'meet', 'you'], translation: 'Mucho gusto' },
        { type: 'match', prompt: 'Une cada frase con su significado', pairs: [['Goodbye', 'Adiós'], ['Thank you', 'Gracias'], ['Good evening', 'Buenas noches (saludo)'], ['See you later', 'Nos vemos']] },
        { type: 'listen', audio: 'Where are you from?', options: ['¿Cómo te llamas?', '¿De dónde eres?', '¿Cómo estás?'], answer: 1 },
        { type: 'truefalse', statement: 'En el diálogo, Carlos es de Bogotá.', answer: false, explanation: 'Carlos dice: "I\'m from Cali".' },
        { type: 'speak', phrase: "Hi, my name is Carlos. I'm from Colombia.", translation: 'Hola, me llamo Carlos. Soy de Colombia.' },
      ],
    },
    {
      objective: 'Pronunciar el alfabeto en inglés y deletrear tu nombre y tu email.',
      slides: [
        { en: 'A, B, C, D, E, F, G', es: 'Las letras se pronuncian distinto que en español.', note: 'A suena "ei", E suena "i".' },
        { en: 'H, I, J, K, L, M, N', es: 'I suena "ai" y J suena "yei".' },
        { en: 'Can you spell that, please?', es: '¿Puedes deletrearlo, por favor?' },
        { en: 'My name is Ana. A, N, A.', es: 'Mi nombre es Ana: A, N, A.' },
        { en: 'My email is ana at gmail dot com.', es: 'Mi correo es ana arroba gmail punto com.', note: '@ = at, . = dot' },
      ],
      vocabulary: [
        { en: 'Spell', es: 'Deletrear', example: 'How do you spell your name?', emoji: '🔤' },
        { en: 'Letter', es: 'Letra', example: 'The first letter is A.', emoji: '🅰️' },
        { en: 'At (@)', es: 'Arroba', example: 'laura at gmail dot com', emoji: '📧' },
        { en: 'Dot (.)', es: 'Punto (en emails)', example: 'gmail dot com', emoji: '⚫' },
        { en: 'Double', es: 'Doble (letra repetida)', example: 'Anna: A, double N, A.', emoji: '✌️' },
        { en: 'Underscore (_)', es: 'Guion bajo', example: 'juan underscore perez', emoji: '➖' },
      ],
      grammar: {
        title: 'Letras que confunden a los hispanohablantes',
        explanation:
          'Las vocales en inglés se nombran distinto: A (ei), E (i), I (ai), O (ou), U (iu). También cuidado con G (yi) y J (yei), que son casi al revés de lo que esperas. Para letras repetidas se dice "double": "Anna" se deletrea "A, double N, A".',
        examples: [
          { en: 'E as in English.', es: 'E de English (suena "i").' },
          { en: 'I as in ice.', es: 'I de ice (suena "ai").' },
          { en: 'G as in good, J as in job.', es: 'G suena "yi", J suena "yei".' },
        ],
        tip: 'En llamadas, aclara letras con palabras: "B as in boy, V as in victory".',
      },
      dialogue: {
        title: 'Inscripción por teléfono',
        lines: [
          { speaker: 'Agent', en: "What's your last name, please?", es: '¿Cuál es tu apellido, por favor?' },
          { speaker: 'Sofía', en: 'Vélez.', es: 'Vélez.' },
          { speaker: 'Agent', en: 'Can you spell that, please?', es: '¿Puedes deletrearlo, por favor?' },
          { speaker: 'Sofía', en: 'Sure. V as in victory, E, L, E, Z.', es: 'Claro. V de victoria, E, L, E, Z.' },
          { speaker: 'Agent', en: 'And your email?', es: '¿Y tu correo?' },
          { speaker: 'Sofía', en: 'sofia dot velez at gmail dot com.', es: 'sofia punto velez arroba gmail punto com.' },
        ],
      },
      exercises: [
        { type: 'choice', prompt: '¿Cómo se pronuncia la letra "I" en inglés?', options: ['"i"', '"ai"', '"ei"'], answer: 1 },
        { type: 'choice', prompt: '¿Cómo dices "@" en un email?', options: ['dot', 'at', 'arroba'], answer: 1 },
        { type: 'fill', sentence: 'Can you ___ your name, please?', answers: ['spell'], hint: 'deletrear' },
        { type: 'listen', audio: 'A, double N, A.', options: ['Ana', 'Anna', 'Annaa'], answer: 1 },
        { type: 'match', pairs: [['E', '"i"'], ['A', '"ei"'], ['J', '"yei"'], ['G', '"yi"']] },
        { type: 'truefalse', statement: 'Sofía deletrea su apellido con la palabra "victory" para aclarar la V.', answer: true },
        { type: 'speak', phrase: 'My name is Sofia. S, O, F, I, A.', translation: 'Me llamo Sofía. S, O, F, I, A.' },
      ],
    },
    {
      objective: 'Usar números del 1 al 1.000 para precios, edades y números de teléfono.',
      slides: [
        { en: 'One, two, three, four, five.', es: 'Uno, dos, tres, cuatro, cinco.' },
        { en: 'Thirteen or thirty?', es: '¿13 o 30?', note: 'En "thirTEEN" el acento va al final; en "THIRty", al inicio.' },
        { en: 'How much is it?', es: '¿Cuánto cuesta?' },
        { en: "It's twenty-five dollars.", es: 'Cuesta veinticinco dólares.' },
        { en: "I'm twenty-eight years old.", es: 'Tengo veintiocho años.', note: 'La edad se dice con "to be", no con "have".' },
      ],
      vocabulary: [
        { en: 'How much', es: 'Cuánto (precio)', example: 'How much is this coffee?', emoji: '💰' },
        { en: 'Price', es: 'Precio', example: 'The price is ten dollars.', emoji: '🏷️' },
        { en: 'Cheap', es: 'Barato', example: 'This phone is cheap.', emoji: '👍' },
        { en: 'Expensive', es: 'Caro', example: 'The hotel is expensive.', emoji: '💸' },
        { en: 'Hundred', es: 'Cien', example: 'One hundred people.', emoji: '💯' },
        { en: 'Thousand', es: 'Mil', example: 'Two thousand pesos.', emoji: '🔢' },
        { en: 'Phone number', es: 'Número de teléfono', example: "What's your phone number?", emoji: '📱' },
      ],
      grammar: {
        title: 'Edad y precios',
        explanation:
          'En inglés la edad se dice con el verbo "to be": "I\'m 25" o "I\'m 25 years old". Nunca "I have 25 years". Para precios se pregunta "How much is it?" (singular) o "How much are they?" (plural).',
        examples: [
          { en: "She's thirty years old.", es: 'Ella tiene treinta años.' },
          { en: 'How much is the ticket?', es: '¿Cuánto cuesta el tiquete?' },
          { en: 'How much are the shoes?', es: '¿Cuánto cuestan los zapatos?' },
          { en: "It's two hundred and fifty pesos.", es: 'Son doscientos cincuenta pesos.' },
        ],
        tip: 'Los números de teléfono se dicen dígito por dígito. El 0 se puede decir "oh": "three-oh-one…".',
      },
      dialogue: {
        title: 'En una tienda de souvenirs',
        lines: [
          { speaker: 'Tourist', en: 'Excuse me, how much is this T-shirt?', es: 'Disculpe, ¿cuánto cuesta esta camiseta?' },
          { speaker: 'Seller', en: "It's fifteen dollars.", es: 'Cuesta quince dólares.' },
          { speaker: 'Tourist', en: 'Fifteen or fifty?', es: '¿Quince o cincuenta?' },
          { speaker: 'Seller', en: 'Fifteen. One, five.', es: 'Quince. Uno, cinco.' },
          { speaker: 'Tourist', en: "Great, that's cheap! I'll take two.", es: '¡Genial, es barata! Me llevo dos.' },
        ],
      },
      exercises: [
        { type: 'choice', prompt: '¿Cómo dices "Tengo 25 años"?', options: ['I have 25 years.', "I'm 25 years old.", 'I am 25 years.'], answer: 1 },
        { type: 'listen', audio: 'It costs thirteen dollars.', options: ['13 dólares', '30 dólares', '3 dólares'], answer: 0 },
        { type: 'listen', audio: 'The room is forty dollars.', options: ['14 dólares', '40 dólares', '4 dólares'], answer: 1 },
        { type: 'fill', sentence: 'How ___ is this coffee?', answers: ['much'] },
        { type: 'match', pairs: [['Cheap', 'Barato'], ['Expensive', 'Caro'], ['Hundred', 'Cien'], ['Thousand', 'Mil']] },
        { type: 'order', words: ['How', 'much', 'are', 'the', 'shoes?'], translation: '¿Cuánto cuestan los zapatos?' },
        { type: 'truefalse', statement: 'La camiseta del diálogo cuesta 50 dólares.', answer: false, explanation: 'Cuesta "fifteen" (15).' },
        { type: 'speak', phrase: 'How much is it?', translation: '¿Cuánto cuesta?' },
      ],
    },
  ],
  // ─── Módulo 2: Mi vida diaria ───────────────────────────────────────────
  [
    {
      objective: 'Hablar de tu rutina diaria con el presente simple.',
      slides: [
        { en: 'I wake up at six.', es: 'Me despierto a las seis.' },
        { en: 'I have breakfast and go to work.', es: 'Desayuno y voy al trabajo.' },
        { en: 'She works in a bank.', es: 'Ella trabaja en un banco.', note: 'Con he/she/it el verbo lleva -s.' },
        { en: "He doesn't drink coffee.", es: 'Él no toma café.' },
        { en: 'Do you study English every day?', es: '¿Estudias inglés todos los días?' },
      ],
      vocabulary: [
        { en: 'Wake up', es: 'Despertarse', example: 'I wake up at 6 a.m.', emoji: '⏰' },
        { en: 'Have breakfast', es: 'Desayunar', example: 'We have breakfast at home.', emoji: '🍳' },
        { en: 'Take a shower', es: 'Bañarse', example: 'I take a shower in the morning.', emoji: '🚿' },
        { en: 'Go to work', es: 'Ir al trabajo', example: 'She goes to work by bus.', emoji: '🚌' },
        { en: 'Have lunch', es: 'Almorzar', example: 'They have lunch at noon.', emoji: '🍽️' },
        { en: 'Go to bed', es: 'Acostarse', example: 'I go to bed at eleven.', emoji: '🛏️' },
        { en: 'Always', es: 'Siempre', example: 'He always arrives early.', emoji: '♾️' },
        { en: 'Never', es: 'Nunca', example: 'I never eat meat.', emoji: '🚫' },
      ],
      grammar: {
        title: 'Presente simple',
        explanation:
          'Se usa para rutinas y hábitos. Con I/you/we/they el verbo queda igual ("I work"). Con he/she/it agregas -s o -es ("she works", "he watches"). Para negar usas "don\'t" o "doesn\'t" + verbo sin -s. Para preguntar, "Do" o "Does" al inicio.',
        examples: [
          { en: 'I work from home.', es: 'Trabajo desde casa.' },
          { en: 'She watches TV at night.', es: 'Ella ve televisión en la noche.' },
          { en: "We don't work on Sundays.", es: 'No trabajamos los domingos.' },
          { en: 'Does he live in Bogotá?', es: '¿Él vive en Bogotá?' },
        ],
        tip: 'Después de "doesn\'t" el verbo pierde la -s: "She doesn\'t work" (no "doesn\'t works").',
      },
      dialogue: {
        title: 'Un día normal',
        lines: [
          { speaker: 'Mateo', en: 'What time do you wake up?', es: '¿A qué hora te despiertas?' },
          { speaker: 'Juliana', en: 'I wake up at five thirty. I go to the gym before work.', es: 'Me despierto a las cinco y media. Voy al gimnasio antes del trabajo.' },
          { speaker: 'Mateo', en: 'Wow! Do you have breakfast at home?', es: '¡Uy! ¿Desayunas en casa?' },
          { speaker: 'Juliana', en: 'No, I have breakfast at the office. And you?', es: 'No, desayuno en la oficina. ¿Y tú?' },
          { speaker: 'Mateo', en: "I wake up at eight. I work from home, so I don't take the bus.", es: 'Me despierto a las ocho. Trabajo desde casa, así que no tomo el bus.' },
        ],
      },
      exercises: [
        { type: 'choice', prompt: 'She ___ in a hospital.', options: ['work', 'works', 'working'], answer: 1 },
        { type: 'fill', sentence: "He ___ drink coffee. He prefers tea.", answers: ["doesn't", 'does not'] },
        { type: 'choice', prompt: '___ you study on weekends?', options: ['Does', 'Do', 'Are'], answer: 1 },
        { type: 'order', words: ['I', 'never', 'eat', 'breakfast', 'at', 'home'], translation: 'Nunca desayuno en casa.' },
        { type: 'match', pairs: [['Wake up', 'Despertarse'], ['Have lunch', 'Almorzar'], ['Go to bed', 'Acostarse'], ['Take a shower', 'Bañarse']] },
        { type: 'truefalse', statement: 'Juliana desayuna en su casa.', answer: false, explanation: 'Ella desayuna en la oficina.' },
        { type: 'listen', audio: 'She goes to work by bus.', options: ['Ella va al trabajo en bus.', 'Ella trabaja en un bus.', 'Ella va a casa en bus.'], answer: 0 },
        { type: 'speak', phrase: 'I wake up at seven and I go to work.', translation: 'Me despierto a las siete y voy al trabajo.' },
      ],
    },
    {
      objective: 'Presentar a tu familia y describir a las personas con adjetivos básicos.',
      slides: [
        { en: 'This is my mother. Her name is Rosa.', es: 'Esta es mi mamá. Se llama Rosa.' },
        { en: 'I have two brothers and one sister.', es: 'Tengo dos hermanos y una hermana.' },
        { en: 'My father is tall and funny.', es: 'Mi papá es alto y gracioso.' },
        { en: "His name is Luis. Her name is Ana.", es: 'Él se llama Luis. Ella se llama Ana.', note: '"His" = de él, "her" = de ella.' },
      ],
      vocabulary: [
        { en: 'Mother / Mom', es: 'Mamá', example: 'My mom is a teacher.', emoji: '👩' },
        { en: 'Father / Dad', es: 'Papá', example: 'My dad works in Cali.', emoji: '👨' },
        { en: 'Brother', es: 'Hermano', example: 'My brother is 20.', emoji: '👦' },
        { en: 'Sister', es: 'Hermana', example: 'Her sister lives in Madrid.', emoji: '👧' },
        { en: 'Grandparents', es: 'Abuelos', example: 'I visit my grandparents on Sundays.', emoji: '👴' },
        { en: 'Cousin', es: 'Primo / prima', example: 'My cousin speaks English.', emoji: '🧑' },
        { en: 'Tall', es: 'Alto', example: 'My brother is very tall.', emoji: '📏' },
        { en: 'Kind', es: 'Amable', example: 'My grandmother is very kind.', emoji: '💛' },
      ],
      grammar: {
        title: 'Posesivos y "have"',
        explanation:
          'Los adjetivos posesivos van antes del sustantivo: my (mi), your (tu), his (su, de él), her (su, de ella), our (nuestro), their (su, de ellos). Para decir cuántos familiares tienes usas "have": "I have two sisters". Con he/she es "has".',
        examples: [
          { en: 'My sister is a doctor.', es: 'Mi hermana es médica.' },
          { en: 'His wife is from Pereira.', es: 'Su esposa (de él) es de Pereira.' },
          { en: 'She has three children.', es: 'Ella tiene tres hijos.' },
          { en: 'Their house is big.', es: 'Su casa (de ellos) es grande.' },
        ],
        tip: 'En inglés el adjetivo va antes del sustantivo: "a kind man", no "a man kind".',
      },
      dialogue: {
        title: 'Mirando fotos',
        lines: [
          { speaker: 'Emma', en: 'Who is this?', es: '¿Quién es?' },
          { speaker: 'David', en: "That's my sister, Camila. She's a nurse.", es: 'Es mi hermana, Camila. Es enfermera.' },
          { speaker: 'Emma', en: 'She looks very kind. And the man next to her?', es: 'Se ve muy amable. ¿Y el hombre a su lado?' },
          { speaker: 'David', en: "That's her husband, Andrés. They have a baby.", es: 'Es su esposo, Andrés. Tienen un bebé.' },
          { speaker: 'Emma', en: 'How cute! Do you have more brothers or sisters?', es: '¡Qué lindo! ¿Tienes más hermanos?' },
          { speaker: 'David', en: "No, it's just me and Camila.", es: 'No, solo somos Camila y yo.' },
        ],
      },
      exercises: [
        { type: 'choice', prompt: 'Este es Juan. ___ wife is Colombian.', options: ['Her', 'His', 'Their'], answer: 1 },
        { type: 'fill', sentence: 'She ___ two children.', answers: ['has'] },
        { type: 'match', pairs: [['Brother', 'Hermano'], ['Cousin', 'Primo'], ['Grandparents', 'Abuelos'], ['Kind', 'Amable']] },
        { type: 'order', words: ['My', 'father', 'is', 'tall', 'and', 'funny'], translation: 'Mi papá es alto y gracioso.' },
        { type: 'truefalse', statement: 'Camila es enfermera.', answer: true },
        { type: 'truefalse', statement: 'David tiene tres hermanos.', answer: false, explanation: '"It\'s just me and Camila": solo una hermana.' },
        { type: 'listen', audio: 'Their house is very big.', options: ['Su casa es muy grande.', 'Mi casa es muy grande.', 'Tu casa es muy bonita.'], answer: 0 },
        { type: 'speak', phrase: 'I have one brother and two sisters.', translation: 'Tengo un hermano y dos hermanas.' },
      ],
    },
    {
      objective: 'Pedir comida en un restaurante y hablar de lo que te gusta comer.',
      slides: [
        { en: "Can I see the menu, please?", es: '¿Puedo ver el menú, por favor?' },
        { en: "I'd like a chicken sandwich.", es: 'Quisiera un sándwich de pollo.', note: '"I\'d like" es más amable que "I want".' },
        { en: 'Anything to drink?', es: '¿Algo de tomar?' },
        { en: 'Can I have the check, please?', es: '¿Me trae la cuenta, por favor?' },
        { en: 'I love pizza, but I don\'t like fish.', es: 'Me encanta la pizza, pero no me gusta el pescado.' },
      ],
      vocabulary: [
        { en: 'Menu', es: 'Menú / carta', example: "Here's the menu.", emoji: '📋' },
        { en: 'Order', es: 'Pedir (comida)', example: 'Are you ready to order?', emoji: '📝' },
        { en: 'Check / Bill', es: 'Cuenta', example: 'The check, please.', emoji: '🧾' },
        { en: 'Tip', es: 'Propina', example: 'We leave a 10% tip.', emoji: '💵' },
        { en: 'Chicken', es: 'Pollo', example: 'I\'d like chicken and rice.', emoji: '🍗' },
        { en: 'Water', es: 'Agua', example: 'A glass of water, please.', emoji: '💧' },
        { en: 'Delicious', es: 'Delicioso', example: 'The soup is delicious!', emoji: '😋' },
      ],
      grammar: {
        title: 'Pedir con cortesía: "I\'d like" y "Can I have…?"',
        explanation:
          '"I\'d like" (I would like) es la forma educada de pedir algo. "Can I have…?" también es muy común. Usa "a/an" para cosas contables en singular: "a coffee", "an orange juice" ("an" antes de sonido de vocal).',
        examples: [
          { en: "I'd like a coffee, please.", es: 'Quisiera un café, por favor.' },
          { en: 'Can I have an orange juice?', es: '¿Me da un jugo de naranja?' },
          { en: "I'd like the soup, please.", es: 'Quisiera la sopa, por favor.' },
        ],
        tip: 'En Estados Unidos es normal dejar entre 15% y 20% de propina.',
      },
      dialogue: {
        title: 'En el restaurante',
        lines: [
          { speaker: 'Waiter', en: 'Hi! Are you ready to order?', es: '¡Hola! ¿Listos para pedir?' },
          { speaker: 'Valeria', en: "Yes. I'd like the chicken salad, please.", es: 'Sí. Quisiera la ensalada de pollo, por favor.' },
          { speaker: 'Waiter', en: 'Sure. Anything to drink?', es: 'Claro. ¿Algo de tomar?' },
          { speaker: 'Valeria', en: 'Can I have a lemonade?', es: '¿Me trae una limonada?' },
          { speaker: 'Waiter', en: 'Of course. Anything else?', es: 'Por supuesto. ¿Algo más?' },
          { speaker: 'Valeria', en: "No, that's all. Thank you!", es: 'No, eso es todo. ¡Gracias!' },
        ],
      },
      exercises: [
        { type: 'choice', prompt: 'La forma más amable de pedir es:', options: ['I want water.', "I'd like some water, please.", 'Give me water.'], answer: 1 },
        { type: 'fill', sentence: 'Can I have ___ orange juice?', answers: ['an'], hint: 'Antes de sonido de vocal' },
        { type: 'order', words: ['Can', 'I', 'have', 'the', 'check,', 'please?'], translation: '¿Me trae la cuenta, por favor?' },
        { type: 'match', pairs: [['Check', 'Cuenta'], ['Tip', 'Propina'], ['Order', 'Pedir'], ['Delicious', 'Delicioso']] },
        { type: 'truefalse', statement: 'Valeria pide una limonada.', answer: true },
        { type: 'listen', audio: 'Are you ready to order?', options: ['¿Quieren la cuenta?', '¿Están listos para pedir?', '¿Les gustó la comida?'], answer: 1 },
        { type: 'speak', phrase: "I'd like the chicken salad, please.", translation: 'Quisiera la ensalada de pollo, por favor.' },
      ],
    },
  ],
  // ─── Módulo 3: Salir al mundo ───────────────────────────────────────────
  [
    {
      objective: 'Pedir y dar direcciones para moverte en una ciudad.',
      slides: [
        { en: 'Excuse me, where is the bank?', es: 'Disculpe, ¿dónde queda el banco?' },
        { en: 'Go straight and turn left.', es: 'Siga derecho y gire a la izquierda.' },
        { en: "It's next to the pharmacy.", es: 'Queda al lado de la farmacia.' },
        { en: "It's across from the park.", es: 'Queda frente al parque.' },
        { en: 'Is it far?', es: '¿Queda lejos?' },
      ],
      vocabulary: [
        { en: 'Turn left / right', es: 'Girar a la izquierda / derecha', example: 'Turn right at the corner.', emoji: '↩️' },
        { en: 'Go straight', es: 'Seguir derecho', example: 'Go straight for two blocks.', emoji: '⬆️' },
        { en: 'Corner', es: 'Esquina', example: "It's on the corner.", emoji: '📐' },
        { en: 'Block', es: 'Cuadra', example: 'Walk three blocks.', emoji: '🏙️' },
        { en: 'Next to', es: 'Al lado de', example: 'The café is next to the bank.', emoji: '↔️' },
        { en: 'Across from', es: 'Frente a', example: "It's across from the station.", emoji: '🔁' },
        { en: 'Near / Far', es: 'Cerca / Lejos', example: 'Is the museum near here?', emoji: '📍' },
      ],
      grammar: {
        title: 'Imperativo para dar instrucciones',
        explanation:
          'Para dar direcciones se usa el imperativo: el verbo solo, sin sujeto. "Go straight", "Turn left", "Take the second street". Para hacerlo más amable, agrega "please" o empieza con "Just…".',
        examples: [
          { en: 'Take the first street on the right.', es: 'Tome la primera calle a la derecha.' },
          { en: 'Walk two blocks.', es: 'Camine dos cuadras.' },
          { en: "Don't cross the bridge.", es: 'No cruce el puente.' },
        ],
        tip: 'Para empezar a preguntar, "Excuse me" es la forma más educada de llamar la atención de un desconocido.',
      },
      dialogue: {
        title: 'Buscando el museo',
        lines: [
          { speaker: 'Tourist', en: 'Excuse me, is the museum near here?', es: 'Disculpe, ¿el museo queda cerca?' },
          { speaker: 'Local', en: "Yes, it's about ten minutes on foot.", es: 'Sí, queda a unos diez minutos a pie.' },
          { speaker: 'Local', en: 'Go straight for two blocks and turn left at the bank.', es: 'Siga derecho dos cuadras y gire a la izquierda en el banco.' },
          { speaker: 'Local', en: "The museum is across from the park.", es: 'El museo queda frente al parque.' },
          { speaker: 'Tourist', en: 'Thank you so much!', es: '¡Muchas gracias!' },
        ],
      },
      exercises: [
        { type: 'choice', prompt: '"Queda al lado del banco" en inglés es:', options: ["It's across from the bank.", "It's next to the bank.", "It's far from the bank."], answer: 1 },
        { type: 'fill', sentence: 'Go straight and ___ left at the corner.', answers: ['turn'] },
        { type: 'order', words: ['Excuse', 'me,', 'where', 'is', 'the', 'station?'], translation: 'Disculpe, ¿dónde está la estación?' },
        { type: 'match', pairs: [['Corner', 'Esquina'], ['Block', 'Cuadra'], ['Near', 'Cerca'], ['Across from', 'Frente a']] },
        { type: 'truefalse', statement: 'El museo queda a diez minutos caminando.', answer: true },
        { type: 'listen', audio: 'Turn right at the second street.', options: ['Gire a la izquierda en la primera calle.', 'Gire a la derecha en la segunda calle.', 'Siga derecho dos calles.'], answer: 1 },
        { type: 'speak', phrase: 'Excuse me, is the bank near here?', translation: 'Disculpe, ¿el banco queda cerca?' },
      ],
    },
    {
      objective: 'Resolver el check-in, migración y preguntas típicas en un aeropuerto.',
      slides: [
        { en: 'Can I see your passport, please?', es: '¿Me muestra su pasaporte, por favor?' },
        { en: 'Window or aisle seat?', es: '¿Silla de ventana o pasillo?' },
        { en: "I'm here on vacation for two weeks.", es: 'Estoy aquí de vacaciones por dos semanas.' },
        { en: 'Where is gate twelve?', es: '¿Dónde queda la puerta doce?' },
        { en: 'My flight is delayed.', es: 'Mi vuelo está retrasado.' },
      ],
      vocabulary: [
        { en: 'Passport', es: 'Pasaporte', example: 'Here is my passport.', emoji: '🛂' },
        { en: 'Boarding pass', es: 'Pase de abordar', example: 'Can I see your boarding pass?', emoji: '🎫' },
        { en: 'Gate', es: 'Puerta de embarque', example: 'Boarding is at gate 5.', emoji: '🚪' },
        { en: 'Luggage', es: 'Equipaje', example: 'I have two pieces of luggage.', emoji: '🧳' },
        { en: 'Carry-on', es: 'Equipaje de mano', example: 'Only one carry-on bag.', emoji: '🎒' },
        { en: 'Delayed', es: 'Retrasado', example: 'The flight is delayed one hour.', emoji: '⏳' },
        { en: 'Aisle', es: 'Pasillo', example: "I'd like an aisle seat.", emoji: '💺' },
      ],
      grammar: {
        title: 'Responder preguntas de migración',
        explanation:
          'En migración las preguntas son cortas y directas. Responde igual: corto y claro. Usa "I\'m here for…" para el motivo y "for + tiempo" para la duración. No necesitas frases largas.',
        examples: [
          { en: 'What is the purpose of your visit? — Tourism.', es: '¿Cuál es el motivo de su visita? — Turismo.' },
          { en: 'How long are you staying? — For ten days.', es: '¿Cuánto tiempo se queda? — Diez días.' },
          { en: 'Where are you staying? — At a hotel in Miami.', es: '¿Dónde se va a hospedar? — En un hotel en Miami.' },
        ],
        tip: 'Ten a la mano la dirección del hotel y el tiquete de regreso: casi siempre los preguntan.',
      },
      dialogue: {
        title: 'En migración',
        lines: [
          { speaker: 'Officer', en: 'Good afternoon. Passport, please.', es: 'Buenas tardes. Pasaporte, por favor.' },
          { speaker: 'Andrés', en: 'Here you go.', es: 'Aquí tiene.' },
          { speaker: 'Officer', en: 'What is the purpose of your visit?', es: '¿Cuál es el motivo de su visita?' },
          { speaker: 'Andrés', en: "Tourism. I'm visiting my cousin.", es: 'Turismo. Voy a visitar a mi primo.' },
          { speaker: 'Officer', en: 'How long are you staying?', es: '¿Cuánto tiempo se va a quedar?' },
          { speaker: 'Andrés', en: 'For two weeks.', es: 'Dos semanas.' },
          { speaker: 'Officer', en: 'Enjoy your stay.', es: 'Disfrute su estadía.' },
        ],
      },
      exercises: [
        { type: 'choice', prompt: 'Quieres la silla junto al pasillo. Dices:', options: ["I'd like a window seat.", "I'd like an aisle seat.", "I'd like a gate seat."], answer: 1 },
        { type: 'fill', sentence: "I'm staying ___ two weeks.", answers: ['for'] },
        { type: 'match', pairs: [['Luggage', 'Equipaje'], ['Gate', 'Puerta de embarque'], ['Delayed', 'Retrasado'], ['Boarding pass', 'Pase de abordar']] },
        { type: 'order', words: ['What', 'is', 'the', 'purpose', 'of', 'your', 'visit?'], translation: '¿Cuál es el motivo de su visita?' },
        { type: 'truefalse', statement: 'Andrés viaja por trabajo.', answer: false, explanation: 'Viaja por turismo, a visitar a su primo.' },
        { type: 'listen', audio: 'Your flight is delayed one hour.', options: ['Su vuelo está cancelado.', 'Su vuelo está retrasado una hora.', 'Su vuelo sale en una hora.'], answer: 1 },
        { type: 'speak', phrase: "I'm here on vacation for ten days.", translation: 'Estoy de vacaciones por diez días.' },
      ],
    },
    {
      objective: 'Mantener tu primera conversación completa: presentarte, preguntar y responder.',
      slides: [
        { en: 'Hi! How are you doing?', es: '¡Hola! ¿Cómo vas?' },
        { en: 'What do you do?', es: '¿A qué te dedicas?' },
        { en: "I'm a designer. I work for a small company.", es: 'Soy diseñador. Trabajo en una empresa pequeña.' },
        { en: 'What do you like to do on weekends?', es: '¿Qué te gusta hacer los fines de semana?' },
        { en: 'It was great talking to you!', es: '¡Qué bueno hablar contigo!' },
      ],
      vocabulary: [
        { en: 'How are you doing?', es: '¿Cómo vas?', example: "Hey Sam, how are you doing?", emoji: '🙂' },
        { en: 'Pretty good', es: 'Bastante bien', example: "I'm pretty good, thanks.", emoji: '👌' },
        { en: 'What do you do?', es: '¿A qué te dedicas?', example: 'So, what do you do?', emoji: '💼' },
        { en: 'Weekend', es: 'Fin de semana', example: 'I play soccer on weekends.', emoji: '📅' },
        { en: 'Hobby', es: 'Pasatiempo', example: 'My hobby is cooking.', emoji: '🎨' },
        { en: 'Me too', es: 'Yo también', example: 'I love salsa! — Me too!', emoji: '🙋' },
      ],
      grammar: {
        title: 'Preguntas para que la conversación no muera',
        explanation:
          'El secreto de una buena conversación es responder y devolver la pregunta. Después de responder, agrega "And you?" o "What about you?". Las preguntas con What, Where, How y Do te sirven para casi todo.',
        examples: [
          { en: "I'm from Bogotá. What about you?", es: 'Soy de Bogotá. ¿Y tú?' },
          { en: 'Do you like music?', es: '¿Te gusta la música?' },
          { en: 'How long have you lived here?', es: '¿Hace cuánto vives aquí?' },
        ],
        tip: 'Si no entiendes, no pasa nada: "Sorry, can you say that again?" o "Can you speak more slowly, please?".',
      },
      dialogue: {
        title: 'Conociendo a alguien en un evento',
        lines: [
          { speaker: 'Sam', en: "Hi! I'm Sam. Is this your first time here?", es: '¡Hola! Soy Sam. ¿Es tu primera vez aquí?' },
          { speaker: 'Laura', en: "Yes, it is! I'm Laura. Nice to meet you.", es: '¡Sí! Soy Laura. Mucho gusto.' },
          { speaker: 'Sam', en: 'Nice to meet you too. What do you do, Laura?', es: 'Igualmente. ¿A qué te dedicas, Laura?' },
          { speaker: 'Laura', en: "I'm a nurse. What about you?", es: 'Soy enfermera. ¿Y tú?' },
          { speaker: 'Sam', en: "I'm a teacher. Do you like dancing?", es: 'Soy profesor. ¿Te gusta bailar?' },
          { speaker: 'Laura', en: 'I love it! I dance salsa every Friday.', es: '¡Me encanta! Bailo salsa todos los viernes.' },
          { speaker: 'Sam', en: 'Me too! Maybe we can go together sometime.', es: '¡Yo también! Quizás podemos ir juntos alguna vez.' },
        ],
      },
      exercises: [
        { type: 'choice', prompt: 'Alguien te pregunta "What do you do?". Responde:', options: ["I'm fine, thanks.", "I'm an engineer.", "I'm from Cali."], answer: 1 },
        { type: 'fill', sentence: "I'm from Cartagena. What ___ you?", answers: ['about'] },
        { type: 'order', words: ['Can', 'you', 'speak', 'more', 'slowly,', 'please?'], translation: '¿Puedes hablar más despacio, por favor?' },
        { type: 'match', pairs: [['Me too', 'Yo también'], ['Hobby', 'Pasatiempo'], ['Pretty good', 'Bastante bien'], ['Weekend', 'Fin de semana']] },
        { type: 'truefalse', statement: 'Laura baila salsa los viernes.', answer: true },
        { type: 'truefalse', statement: 'Sam es enfermero.', answer: false, explanation: 'Sam es profesor ("I\'m a teacher").' },
        { type: 'listen', audio: 'Sorry, can you say that again?', options: ['Perdón, ¿puedes repetirlo?', 'Perdón, ¿puedes ayudarme?', 'Perdón, no entiendo inglés.'], answer: 0 },
        { type: 'speak', phrase: "I'm a designer. What about you?", translation: 'Soy diseñador. ¿Y tú?' },
      ],
    },
  ],
];
