import type { LessonExtras } from './types.js';

/** Inglés desde Cero (A1): lectura, errores típicos, pronunciación, cultura, misión y práctica extra. */
export const inglesDesdeCeroExtras: LessonExtras[][] = [
  // ─── Módulo 1: Primeros pasos ───────────────────────────────────────────
  [
    // M1L1 · Saludos y presentaciones
    {
      vocabulary: [
        { en: 'Hi there', es: 'Hola (muy informal)', example: 'Hi there! Are you new here?', emoji: '🙋' },
        { en: 'How are you?', es: '¿Cómo estás?', example: "Hi Ana, how are you? — I'm fine, thanks.", emoji: '😊' },
        { en: 'Fine', es: 'Bien', example: "I'm fine, thank you. And you?", emoji: '👌' },
        { en: 'Welcome', es: 'Bienvenido(a)', example: 'Welcome to Colombia!', emoji: '🎉' },
        { en: 'See you tomorrow', es: 'Nos vemos mañana', example: 'Bye, Laura! See you tomorrow.', emoji: '📅' },
        { en: 'Friend', es: 'Amigo(a)', example: 'This is my friend Pedro.', emoji: '🧑‍🤝‍🧑' },
      ],
      mistakes: [
        { wrong: 'I have 25 years.', right: "I'm 25.", why: 'La edad va con "to be" (am/is/are), nunca con "have". Lo verás a fondo en la lección de números.' },
        { wrong: 'Good night! (al llegar a una reunión a las 8 p. m.)', right: 'Good evening!', why: '"Good night" es solo para despedirte o irte a dormir. Para saludar de noche usa "Good evening" o simplemente "Hi".' },
        { wrong: 'My name is Carlos and I am from Colombia, I am colombian.', right: "My name is Carlos. I'm Colombian.", why: 'Las nacionalidades y los idiomas van siempre con mayúscula en inglés: Colombian, Spanish, English.' },
        { wrong: 'Nice to meet you too. (cuando la otra persona aún no lo ha dicho)', right: 'Nice to meet you.', why: '"Too" significa "también": solo se usa para responder cuando la otra persona ya dijo "Nice to meet you".' },
      ],
      pronunciation: {
        focus: 'La H aspirada y el sonido "th"',
        tip: 'En español la H es muda, pero en inglés suena como un suspiro suave: "Hello" se dice /jelou/ con aire, no "elou". Y "th" de "thank you" se hace poniendo la punta de la lengua entre los dientes y soplando.',
        words: [
          { word: 'Hello', sounds: '/həˈloʊ/ — "je-LOU"', es: 'Hola' },
          { word: 'Hi', sounds: '/haɪ/ — "jai"', es: 'Hola' },
          { word: 'Thank you', sounds: '/ˈθæŋk juː/ — "THANK-iu"', es: 'Gracias' },
          { word: 'Morning', sounds: '/ˈmɔːrnɪŋ/ — "MOR-ning"', es: 'Mañana' },
          { word: 'Evening', sounds: '/ˈiːvnɪŋ/ — "IV-ning"', es: 'Noche (temprano)' },
        ],
      },
      reading: {
        title: 'A new student',
        paragraphs: [
          "Hi! My name is Daniela. I'm twenty years old and I'm from Bogotá, Colombia. I'm a student. I study engineering at a university in my city.",
          "Today is my first English class. The teacher's name is Mark. He's from Canada. He's very friendly. In the class there are twelve students. My new friend is Andrés. He's from Pasto.",
          "At the end of the class, the teacher says: \"Goodbye, everyone! See you on Thursday.\" I say: \"Bye, Mark! Thank you!\"",
        ],
        glossary: [
          { en: 'student', es: 'estudiante' },
          { en: 'friendly', es: 'amable, simpático' },
          { en: 'there are', es: 'hay (plural)' },
          { en: 'everyone', es: 'todos' },
        ],
        questions: [
          { q: 'Where is Daniela from?', options: ['Pasto', 'Bogotá', 'Canada'], answer: 1 },
          { q: 'Who is Mark?', options: ['A student', 'The teacher', "Daniela's brother"], answer: 1 },
          { q: 'How many students are in the class?', options: ['Twenty', 'Two', 'Twelve'], answer: 2, explanation: '"Twelve" = 12. "Twenty" = 20.' },
          { q: 'When is the next class?', options: ['On Thursday', 'Tomorrow', 'On Monday'], answer: 0 },
        ],
      },
      culture: {
        title: 'Cómo se saluda en países de habla inglesa',
        body: 'En Estados Unidos, Canadá y Reino Unido no se saluda de beso. Entre colegas o al conocer a alguien se da la mano con firmeza y se mira a los ojos. Entre amigos basta con "Hey!" o un abrazo corto. Y ojo: "How are you?" muchas veces es solo un saludo, no una pregunta real. La respuesta esperada es corta: "Good, thanks! You?"',
      },
      mission: {
        title: 'Tu presentación de 20 segundos',
        task: 'Graba un audio o video (con el celular) presentándote en inglés. Escúchalo y repítelo hasta que te salga sin leer.',
        steps: ['Saluda según la hora del día', 'Di tu nombre y de dónde eres', 'Di una cosa más sobre ti (estudiante, trabajo…)', 'Despídete'],
        model: "Good morning! My name is Camila. I'm from Barranquilla, Colombia. I'm a nurse and I'm learning English. Nice to meet you! Bye!",
      },
      exercises: [
        { type: 'dictation', audio: "Hi, I'm Laura.", translation: 'Hola, soy Laura.' },
        { type: 'fix', sentence: 'Good night! Welcome to the meeting.', answers: ['Good evening! Welcome to the meeting.', 'Hi! Welcome to the meeting.', 'Hello! Welcome to the meeting.'], explanation: 'Al llegar se dice "Good evening"; "Good night" es para despedirse.' },
        { type: 'choice', prompt: 'Alguien te dice "Nice to meet you!". ¿Qué respondes?', options: ['Nice to meet you too!', 'Good night!', "I'm fine."], answer: 0 },
        { type: 'dictation', audio: 'Where are you from?', translation: '¿De dónde eres?' },
        { type: 'fix', sentence: "I'm colombian.", answers: ["I'm Colombian.", 'I am Colombian.'], explanation: 'Las nacionalidades van con mayúscula.' },
        { type: 'listen', audio: 'See you tomorrow!', options: ['¡Nos vemos mañana!', '¡Buenos días!', '¡Mucho gusto!'], answer: 0 },
        { type: 'fill', sentence: 'How ___ you? — Fine, thanks.', answers: ['are'], hint: 'verbo to be con "you"' },
        { type: 'order', words: ['I', 'am', 'from', 'Medellín'], translation: 'Soy de Medellín.' },
        { type: 'choice', prompt: 'Son las 9:00 p. m. y te vas a dormir. ¿Qué dices?', options: ['Good evening', 'Good night', 'Good afternoon'], answer: 1 },
        { type: 'truefalse', statement: '"How are you?" casi siempre espera una respuesta larga sobre tu día.', answer: false, explanation: 'Suele ser un saludo: basta con "Good, thanks. You?".' },
      ],
    },
    // M1L2 · El alfabeto
    {
      vocabulary: [
        { en: 'Capital letter', es: 'Mayúscula', example: 'Names start with a capital letter.', emoji: '🔠' },
        { en: 'Lowercase', es: 'Minúscula', example: 'Write your email in lowercase.', emoji: '🔡' },
        { en: 'Hyphen / dash (-)', es: 'Guion', example: 'maria-lopez at gmail dot com', emoji: '➖' },
        { en: 'Last name', es: 'Apellido', example: 'My last name is Gómez.', emoji: '🪪' },
        { en: 'First name', es: 'Nombre (de pila)', example: 'My first name is Juan.', emoji: '🏷️' },
        { en: 'Slash (/)', es: 'Barra (en páginas web)', example: 'www dot site dot com slash courses', emoji: '↗️' },
      ],
      mistakes: [
        { wrong: 'My email is ana arroba gmail punto com.', right: 'My email is ana at gmail dot com.', why: '@ se dice "at" y el punto de los correos y páginas web se dice "dot" (no "point" ni "period").' },
        { wrong: 'How do you write your name? (para pedir que deletreen)', right: 'How do you spell your name?', why: 'Para pedir letra por letra se usa "spell". "Write" es escribir en general.' },
        { wrong: 'My name is Ana. A, N, A. (diciendo las letras como en español)', right: 'My name is Ana. "Ei", "en", "ei".', why: 'Las vocales cambian: la A suena "ei" y la E suena "i". Si las dices en español, te van a anotar otra letra.' },
      ],
      pronunciation: {
        focus: 'Las vocales del alfabeto',
        tip: 'Memoriza las cinco vocales como un grupo: A /ei/, E /i/, I /ai/, O /ou/, U /iu/. Casi todos los errores al deletrear vienen de la E y la I, que están "al revés" frente al español.',
        words: [
          { word: 'A', sounds: '/eɪ/ — "ei"' },
          { word: 'E', sounds: '/iː/ — "i"' },
          { word: 'I', sounds: '/aɪ/ — "ai"' },
          { word: 'O', sounds: '/oʊ/ — "ou"' },
          { word: 'U', sounds: '/juː/ — "iu"' },
          { word: 'R', sounds: '/ɑːr/ — "ar"' },
          { word: 'Y', sounds: '/waɪ/ — "uai"' },
        ],
      },
      reading: {
        title: 'At the hotel reception',
        paragraphs: [
          'Julián is in Miami for a conference. He arrives at the hotel at nine p.m. The receptionist is very nice. She asks for his name and his passport.',
          "\"My name is Julián Reyes,\" he says. \"Can you spell your last name, please?\" she asks. \"Sure. R, E, Y, E, S.\" The receptionist writes \"Rayes\". Julián smiles and says: \"No, sorry. It's E, not A. R, E, Y, E, S.\"",
          "Finally, she asks for his email. \"It's julian underscore reyes at outlook dot com.\" The receptionist gives him the key. His room is number two hundred and four.",
        ],
        glossary: [
          { en: 'arrives', es: 'llega' },
          { en: 'asks for', es: 'pide' },
          { en: 'writes', es: 'escribe' },
          { en: 'key', es: 'llave' },
        ],
        questions: [
          { q: 'Why is Julián in Miami?', options: ['For a conference', 'On vacation', 'To study'], answer: 0 },
          { q: 'What mistake does the receptionist make?', options: ['She writes A instead of E', 'She writes his first name wrong', 'She gives him the wrong key'], answer: 0 },
          { q: 'What symbol is in his email?', options: ['A hyphen (-)', 'An underscore (_)', 'A slash (/)'], answer: 1 },
          { q: "What's his room number?", options: ['240', '204', '24'], answer: 1, explanation: '"Two hundred and four" = 204.' },
        ],
      },
      culture: {
        title: 'El alfabeto fonético de la radio',
        body: 'En aeropuertos, call centers y bancos usan palabras clave para no confundir letras: A de Alpha, B de Bravo, C de Charlie, D de Delta, E de Echo… No necesitas memorizarlo, pero sí usar el truco: "M as in Mexico, N as in Nicaragua". Con nombres latinos como "Yuliana" o "Jhon", deletrear bien te evita errores en tiquetes y reservas.',
      },
      mission: {
        title: 'Deletrea tu identidad',
        task: 'Escribe y di en voz alta tu nombre completo, tu email y el nombre de tu ciudad, deletreando cada uno como si estuvieras en una llamada.',
        steps: ['Nombre y apellido letra por letra', 'Tu email con at, dot, underscore…', 'Usa "as in" para una letra difícil'],
        model: 'My name is Yuliana Pérez. Y, U, L, I, A, N, A. P, E, R, E, Z — P as in Paris. My email is yuli dot perez at gmail dot com.',
      },
      exercises: [
        { type: 'dictation', audio: 'Can you spell that, please?', translation: '¿Puedes deletrearlo, por favor?' },
        { type: 'listen', audio: 'J, U, A, N.', options: ['Juan', 'Gian', 'Yuan'], answer: 0 },
        { type: 'fix', sentence: 'My email is carlos arroba gmail punto com.', answers: ['My email is carlos at gmail dot com.'], explanation: '@ = at · . = dot' },
        { type: 'choice', prompt: '¿Cómo se pronuncia la letra "E" en inglés?', options: ['"e"', '"i"', '"ei"'], answer: 1 },
        { type: 'listen', audio: 'E, V, A.', options: ['Iva', 'Eva', 'Ava'], answer: 1, },
        { type: 'fill', sentence: 'What is your ___ name? — Gómez.', answers: ['last'], hint: 'apellido = ___ name' },
        { type: 'match', prompt: 'Une el símbolo con su nombre', pairs: [['@', 'at'], ['.', 'dot'], ['_', 'underscore'], ['-', 'hyphen'], ['/', 'slash']] },
        { type: 'dictation', audio: 'B as in boy.', translation: 'B de boy.' },
        { type: 'fix', sentence: 'How do you write your name? (para que lo deletreen)', answers: ['How do you spell your name?', 'How do you spell your name'], explanation: 'Deletrear = spell.' },
        { type: 'choice', prompt: '¿Qué letra suena "uai"?', options: ['W', 'Y', 'I'], answer: 1 },
      ],
    },
    // M1L3 · Números
    {
      vocabulary: [
        { en: 'Zero / oh', es: 'Cero', example: 'My number is three-oh-one…', emoji: '0️⃣' },
        { en: 'Change', es: 'Vuelto / cambio', example: "Here's your change.", emoji: '🪙' },
        { en: 'Cash', es: 'Efectivo', example: 'Can I pay in cash?', emoji: '💵' },
        { en: 'Credit card', es: 'Tarjeta de crédito', example: 'Do you take credit cards?', emoji: '💳' },
        { en: 'Discount', es: 'Descuento', example: 'Is there a discount?', emoji: '🏷️' },
        { en: 'Half', es: 'Mitad', example: 'Half price today!', emoji: '½' },
      ],
      mistakes: [
        { wrong: 'I have 30 years.', right: "I'm 30 (years old).", why: 'La edad siempre con "to be". "I have 30 years" suena a que tienes 30 años guardados en algún lado.' },
        { wrong: 'Two hundreds dollars.', right: 'Two hundred dollars.', why: '"Hundred", "thousand" y "million" no llevan -s cuando van con un número delante.' },
        { wrong: '1.500 (mil quinientos) escrito igual que en Colombia', right: '1,500', why: 'En inglés la coma separa miles y el punto separa decimales: 1,500 = mil quinientos; 1.5 = uno coma cinco.' },
        { wrong: 'How much costs it?', right: 'How much is it? / How much does it cost?', why: 'La pregunta más natural es "How much is it?". Si usas "cost", necesitas "does".' },
      ],
      pronunciation: {
        focus: '13 vs. 30: dónde va el acento',
        tip: 'Los números en -teen (13-19) se acentúan al final y la "t" suena clara: thir-TEEN. Los terminados en -ty (30, 40…) se acentúan al inicio y en inglés americano la "t" suena casi como una "r" suave: THIR-dy. Exagéralo al principio.',
        words: [
          { word: 'thirteen', sounds: '/θɜːrˈtiːn/ — "zur-TIIN"', es: '13' },
          { word: 'thirty', sounds: '/ˈθɜːrti/ — "ZUR-di"', es: '30' },
          { word: 'fifteen', sounds: '/fɪfˈtiːn/ — "fif-TIIN"', es: '15' },
          { word: 'fifty', sounds: '/ˈfɪfti/ — "FIF-di"', es: '50' },
          { word: 'eighteen', sounds: '/eɪˈtiːn/ — "ei-TIIN"', es: '18' },
          { word: 'eighty', sounds: '/ˈeɪti/ — "EI-di"', es: '80' },
        ],
      },
      reading: {
        title: 'Shopping in New York',
        paragraphs: [
          "Mariana is on vacation in New York. She's thirty-two years old and she loves shopping. Today she's at a big store on Fifth Avenue.",
          "She sees a black jacket. \"Excuse me, how much is this jacket?\" she asks. \"It's one hundred and twenty dollars,\" says the shop assistant. \"That's expensive!\" she thinks. But then the assistant says: \"Today there's a fifty percent discount.\"",
          "So the jacket is sixty dollars. Mariana pays with her credit card. She's very happy. In the evening she sends a photo to her sister in Cartagena.",
        ],
        glossary: [
          { en: 'loves', es: 'le encanta' },
          { en: 'shop assistant', es: 'vendedor(a)' },
          { en: 'pays', es: 'paga' },
          { en: 'sends', es: 'envía' },
        ],
        questions: [
          { q: 'How old is Mariana?', options: ['23', '32', '30'], answer: 1 },
          { q: 'What is the original price of the jacket?', options: ['$120', '$60', '$112'], answer: 0 },
          { q: 'How does Mariana pay?', options: ['In cash', 'With a credit card', 'With her phone'], answer: 1 },
          { q: 'Where does her sister live?', options: ['New York', 'Bogotá', 'Cartagena'], answer: 2 },
        ],
      },
      culture: {
        title: 'Los precios no incluyen el impuesto (y la propina no es opcional)',
        body: 'En Estados Unidos el precio de la etiqueta casi nunca incluye el impuesto (sales tax): un producto de $100 puede salir en $108 en la caja. Además, en restaurantes se espera propina del 15 al 20 % y es prácticamente obligatoria. En Reino Unido, en cambio, el impuesto ya va incluido en el precio.',
      },
      mission: {
        title: 'Simula una compra',
        task: 'Escoge 3 cosas que tengas cerca (un celular, unos zapatos, un café). Invéntales un precio en dólares y dramatiza la compra en voz alta: pregunta el precio, reacciona y paga.',
        steps: ['Pregunta "How much is…?"', 'Di el precio con números en inglés', 'Reacciona: cheap / expensive', 'Di cómo pagas'],
        model: "Excuse me, how much is this coffee? — It's four dollars and fifty cents. — OK, that's cheap. Can I pay with a credit card? — Sure!",
      },
      exercises: [
        { type: 'listen', audio: "It's fifteen dollars.", options: ['$15', '$50', '$5'], answer: 0 },
        { type: 'dictation', audio: 'How much is it?', translation: '¿Cuánto cuesta?' },
        { type: 'fix', sentence: 'I have twenty years.', answers: ["I'm twenty.", 'I am twenty.', "I'm twenty years old.", 'I am twenty years old.'], explanation: 'La edad se dice con "to be".' },
        { type: 'listen', audio: 'Eighty people.', options: ['18 personas', '80 personas', '8 personas'], answer: 1 },
        { type: 'fix', sentence: 'It costs three hundreds dollars.', answers: ['It costs three hundred dollars.'], explanation: '"Hundred" no lleva -s después de un número.' },
        { type: 'choice', prompt: '¿Cómo se escribe "mil quinientos" en inglés?', options: ['1.500', '1,500', '1500,00'], answer: 1 },
        { type: 'dictation', audio: "I'm thirty-two years old.", translation: 'Tengo treinta y dos años.' },
        { type: 'match', prompt: 'Une el número', pairs: [['forty', '40'], ['fourteen', '14'], ['ninety', '90'], ['nineteen', '19']] },
        { type: 'order', words: ['Can', 'I', 'pay', 'in', 'cash?'], translation: '¿Puedo pagar en efectivo?' },
        { type: 'truefalse', statement: 'En EE. UU. el precio de la etiqueta normalmente ya incluye el impuesto.', answer: false, explanation: 'El sales tax se suma en la caja.' },
      ],
    },
  ],
  // ─── Módulo 2: Mi vida diaria ───────────────────────────────────────────
  [
    // M2L1 · Rutina
    {
      vocabulary: [
        { en: 'Usually', es: 'Normalmente', example: 'I usually wake up at six.', emoji: '🔁' },
        { en: 'Sometimes', es: 'A veces', example: 'Sometimes I cook dinner.', emoji: '🎲' },
        { en: 'Get dressed', es: 'Vestirse', example: 'I get dressed after breakfast.', emoji: '👕' },
        { en: 'Commute', es: 'Trayecto al trabajo', example: 'My commute is one hour by bus.', emoji: '🚌' },
        { en: 'Work out', es: 'Hacer ejercicio', example: 'She works out three times a week.', emoji: '🏋️' },
        { en: 'Weekday', es: 'Día entre semana', example: 'On weekdays I work from home.', emoji: '🗓️' },
      ],
      mistakes: [
        { wrong: 'She work in a bank.', right: 'She works in a bank.', why: 'Con he, she e it el verbo en presente simple lleva -s. Es el error número uno de los hispanohablantes.' },
        { wrong: 'I always am tired. / I go always to the gym.', right: "I'm always tired. / I always go to the gym.", why: 'Los adverbios de frecuencia van ANTES del verbo normal, pero DESPUÉS del verbo "to be".' },
        { wrong: 'He don\'t like coffee.', right: "He doesn't like coffee.", why: 'Con he/she/it la negación es "doesn\'t" y el verbo vuelve a su forma base (like, no likes).' },
        { wrong: 'Do she work on Saturdays?', right: 'Does she work on Saturdays?', why: 'Las preguntas con he/she/it usan "Does".' },
      ],
      pronunciation: {
        focus: 'Las tres formas de la -s final',
        tip: 'La -s del presente suena de tres maneras: /s/ después de sonidos sordos (works, eats), /z/ después de sonidos sonoros (goes, plays) e /iz/ después de s, sh, ch, x (watches, washes). No la omitas: en inglés esa -s cambia el significado.',
        words: [
          { word: 'works', sounds: '/wɜːrks/ — termina en "s"' },
          { word: 'goes', sounds: '/goʊz/ — termina en "z"' },
          { word: 'plays', sounds: '/pleɪz/ — termina en "z"' },
          { word: 'watches', sounds: '/ˈwɑːtʃɪz/ — termina en "iz"' },
          { word: 'washes', sounds: '/ˈwɑːʃɪz/ — termina en "iz"' },
        ],
      },
      reading: {
        title: 'A day in the life of a nurse',
        paragraphs: [
          'Paola is a nurse in a hospital in Bucaramanga. Her day starts very early. She wakes up at four thirty, takes a quick shower and has coffee with bread. She never has a big breakfast.',
          'She takes the bus at five fifteen. Her commute is forty minutes. At work she checks patients, gives medicine and talks to doctors. It\'s a hard job, but she loves it.',
          'Paola finishes work at three p.m. In the afternoon she usually picks up her son from school. They have dinner together at seven. She goes to bed at nine because the next day she wakes up early again.',
        ],
        glossary: [
          { en: 'nurse', es: 'enfermera' },
          { en: 'checks', es: 'revisa' },
          { en: 'hard', es: 'difícil, duro' },
          { en: 'picks up', es: 'recoge' },
        ],
        questions: [
          { q: 'What time does Paola wake up?', options: ['At 4:30', 'At 5:15', 'At 3:00'], answer: 0 },
          { q: 'How long is her commute?', options: ['15 minutes', '40 minutes', 'One hour'], answer: 1 },
          { q: 'What does she usually do in the afternoon?', options: ['She works out', 'She picks up her son', 'She sleeps'], answer: 1 },
          { q: 'Why does she go to bed at nine?', options: ["Because she's sick", 'Because she wakes up early', 'Because her son is tired'], answer: 1 },
        ],
      },
      culture: {
        title: '¿A qué hora se cena en EE. UU.?',
        body: 'En Estados Unidos y Canadá la cena (dinner) es temprano: entre las 5:30 y las 7:00 p. m., y suele ser la comida más grande del día. El almuerzo (lunch) es rápido: un sándwich o una ensalada en 20-30 minutos, muchas veces frente al computador. Si te invitan a "dinner at six", llega puntual.',
      },
      mission: {
        title: 'Tu rutina en 6 frases',
        task: 'Escribe tu rutina de un día entre semana con al menos 6 frases y 3 adverbios de frecuencia. Luego cuéntala en voz alta en tercera persona, como si hablaras de otra persona ("He wakes up…").',
        steps: ['Usa horas exactas (at seven thirty)', 'Incluye always / usually / sometimes / never', 'Repite en tercera persona agregando la -s'],
        model: 'I usually wake up at six. I take a shower and get dressed. I never have breakfast at home. I take the Transmilenio at seven. I work from eight to five. I sometimes work out in the evening.',
      },
      exercises: [
        { type: 'fix', sentence: 'My brother work in a hotel.', answers: ['My brother works in a hotel.'], explanation: 'He/she/it → verbo + s.' },
        { type: 'dictation', audio: 'She usually goes to work by bus.', translation: 'Ella normalmente va al trabajo en bus.' },
        { type: 'choice', prompt: 'Elige la frase correcta', options: ['I go always to the gym.', 'I always go to the gym.', 'Always I go to the gym.'], answer: 1 },
        { type: 'fix', sentence: "He don't eat meat.", answers: ["He doesn't eat meat.", 'He does not eat meat.'], explanation: 'He/she/it → doesn\'t + verbo base.' },
        { type: 'fill', sentence: '___ your sister work on Saturdays?', answers: ['Does'], hint: 'pregunta con she' },
        { type: 'listen', audio: 'He never has breakfast.', options: ['Él siempre desayuna.', 'Él nunca desayuna.', 'Él a veces desayuna.'], answer: 1 },
        { type: 'dictation', audio: 'I wake up at seven.', translation: 'Me despierto a las siete.' },
        { type: 'order', words: ['We', 'sometimes', 'have', 'dinner', 'at', 'home'], translation: 'A veces cenamos en casa.' },
        { type: 'choice', prompt: '¿Qué verbo termina con sonido "iz"?', options: ['works', 'watches', 'plays'], answer: 1 },
        { type: 'truefalse', statement: 'En el texto, Paola tiene un desayuno grande todos los días.', answer: false, explanation: '"She never has a big breakfast."' },
      ],
    },
    // M2L2 · Familia y descripciones
    {
      vocabulary: [
        { en: 'Husband / wife', es: 'Esposo / esposa', example: 'My wife is a teacher.', emoji: '💍' },
        { en: 'Son / daughter', es: 'Hijo / hija', example: 'They have a son and a daughter.', emoji: '👶' },
        { en: 'Uncle / aunt', es: 'Tío / tía', example: 'My uncle lives in Spain.', emoji: '🧔' },
        { en: 'Short', es: 'Bajo / corto', example: 'My grandma is short.', emoji: '📏' },
        { en: 'Funny', es: 'Divertido, chistoso', example: 'My cousin is very funny.', emoji: '😂' },
        { en: 'Curly hair', es: 'Pelo crespo', example: 'She has long curly hair.', emoji: '👩‍🦱' },
        { en: 'Only child', es: 'Hijo único', example: "I'm an only child.", emoji: '🧒' },
      ],
      mistakes: [
        { wrong: 'My parents are 3: my mom, my dad and my stepdad.', right: 'I have three parents: my mom, my dad and my stepdad.', why: '"Parents" son solo papá y mamá (o quienes cumplen ese rol). Para "familiares" en general usa "relatives".' },
        { wrong: 'She has 1.60 meters.', right: 'She is 1.60 meters tall.', why: 'La estatura, igual que la edad, va con "to be".' },
        { wrong: 'My sister is very kind and she have blue eyes.', right: 'My sister is very kind and she has blue eyes.', why: '"Have" se vuelve "has" con he/she/it.' },
        { wrong: 'The car of my father is red.', right: "My father's car is red.", why: 'Para la posesión de personas se usa \'s: "my father\'s car", "Ana\'s house".' },
        { wrong: 'She is a person very nice.', right: 'She is a very nice person.', why: 'El adjetivo va ANTES del sustantivo en inglés.' },
      ],
      pronunciation: {
        focus: 'El sonido "th" sonoro: mother, father, brother',
        tip: 'En "mother", "father" y "brother" el "th" vibra: pon la lengua entre los dientes y deja salir la voz, como una "d" suave. No digas "moder" ni "brozer".',
        words: [
          { word: 'mother', sounds: '/ˈmʌðər/ — "MA-der" (lengua entre dientes)', es: 'madre' },
          { word: 'father', sounds: '/ˈfɑːðər/ — "FA-der"', es: 'padre' },
          { word: 'brother', sounds: '/ˈbrʌðər/ — "BRA-der"', es: 'hermano' },
          { word: 'daughter', sounds: '/ˈdɔːtər/ — "DO-der" (la gh no suena)', es: 'hija' },
          { word: 'cousin', sounds: '/ˈkʌzən/ — "KA-zen"', es: 'primo(a)' },
        ],
      },
      reading: {
        title: 'My big Colombian family',
        paragraphs: [
          "My name is Tomás and I have a big family. My parents are Luis and Gloria. My dad is tall and serious, but he's very funny with his friends. My mom is short and has curly hair. She's a doctor.",
          "I have two sisters, Sara and Lina. Sara is older than me; she's married and her husband's name is Felipe. They have a baby daughter, so I'm an uncle! Lina is fifteen and she loves music.",
          "On Sundays the whole family has lunch at my grandparents' house. My grandma cooks sancocho and my grandpa tells old stories. My cousins come too. It's loud, but I love it.",
        ],
        glossary: [
          { en: 'older than', es: 'mayor que' },
          { en: 'married', es: 'casado(a)' },
          { en: 'whole', es: 'entero(a), toda' },
          { en: 'loud', es: 'ruidoso' },
        ],
        questions: [
          { q: "What's Tomás's mother's job?", options: ['Teacher', 'Doctor', 'Musician'], answer: 1 },
          { q: 'Why is Tomás an uncle?', options: ['Lina has a baby', 'Sara has a baby daughter', 'His cousin has a son'], answer: 1 },
          { q: "Who is Felipe?", options: ["Tomás's brother", "Sara's husband", "Tomás's cousin"], answer: 1 },
          { q: 'Where does the family have lunch on Sundays?', options: ["At Tomás's house", 'At a restaurant', "At the grandparents' house"], answer: 2 },
        ],
      },
      culture: {
        title: 'Un solo apellido y "in-laws"',
        body: 'En países de habla inglesa la gente usa un solo apellido (normalmente el del papá), así que en formularios tu "last name" puede generar confusión: escribe ambos apellidos juntos o con guion para evitar problemas. Y para la familia política se agrega "-in-law": mother-in-law (suegra), brother-in-law (cuñado).',
      },
      mission: {
        title: 'Presenta una foto familiar',
        task: 'Busca una foto con tu familia o amigos. Describe a 3 personas: quiénes son, cómo son físicamente y cómo es su personalidad.',
        steps: ['This is my… / These are my…', 'Una descripción física con "is" y otra con "has"', 'Un adjetivo de personalidad'],
        model: "This is my aunt Patricia. She's my mom's sister. She's tall and she has short black hair. She's very funny. These are my cousins, Mateo and Juan. They're twins!",
      },
      exercises: [
        { type: 'fix', sentence: 'She have two brothers.', answers: ['She has two brothers.'], explanation: 'She → has.' },
        { type: 'dictation', audio: 'My sister has curly hair.', translation: 'Mi hermana tiene el pelo crespo.' },
        { type: 'fix', sentence: 'The house of my grandmother is big.', answers: ["My grandmother's house is big."], explanation: 'Posesión con \'s.' },
        { type: 'match', prompt: 'Une el familiar', pairs: [['aunt', 'tía'], ['uncle', 'tío'], ['daughter', 'hija'], ['husband', 'esposo'], ['mother-in-law', 'suegra']] },
        { type: 'choice', prompt: 'Elige el orden correcto', options: ['He is a man very kind.', 'He is a very kind man.', 'He is a kind very man.'], answer: 1 },
        { type: 'listen', audio: "I'm an only child.", options: ['Soy hijo único.', 'Solo tengo un hijo.', 'Soy un niño solo.'], answer: 0 },
        { type: 'dictation', audio: 'My father is tall and funny.', translation: 'Mi papá es alto y divertido.' },
        { type: 'fill', sentence: "My mother's brother is my ___.", answers: ['uncle'], hint: 'tío' },
        { type: 'order', words: ['They', 'have', 'a', 'baby', 'daughter'], translation: 'Ellos tienen una bebé.' },
        { type: 'truefalse', statement: 'Según el texto, Lina es la hermana mayor de Tomás.', answer: false, explanation: 'Sara es la mayor; Lina tiene 15 años.' },
      ],
    },
    // M2L3 · Restaurante
    {
      vocabulary: [
        { en: 'Starter', es: 'Entrada', example: "I'd like soup as a starter.", emoji: '🥣' },
        { en: 'Main course', es: 'Plato fuerte', example: 'For the main course, the steak.', emoji: '🍽️' },
        { en: 'Dessert', es: 'Postre', example: 'Do you have any desserts?', emoji: '🍰' },
        { en: 'Medium rare', es: 'Término medio-rojo (carne)', example: 'Steak, medium rare, please.', emoji: '🥩' },
        { en: 'To go', es: 'Para llevar', example: 'A coffee to go, please.', emoji: '🥡' },
        { en: 'Allergic to', es: 'Alérgico a', example: "I'm allergic to peanuts.", emoji: '⚠️' },
        { en: 'Refill', es: 'Recarga (de bebida)', example: 'Can I get a refill?', emoji: '🥤' },
      ],
      mistakes: [
        { wrong: 'Give me a coffee.', right: "Can I have a coffee, please? / I'd like a coffee, please.", why: '"Give me" suena brusco en inglés. Pedir con "Can I have…?" o "I\'d like…" es lo normal y educado.' },
        { wrong: 'The bill, please! (gritando o chasqueando los dedos)', right: 'Excuse me, could we get the check, please?', why: 'Para pedir la cuenta, haz contacto visual con el mesero y pídela con "could". Chasquear los dedos se considera muy grosero.' },
        { wrong: 'I want the chicken.', right: "I'll have the chicken.", why: '"I want" es correcto pero suena exigente. "I\'ll have…" es la forma típica de ordenar.' },
        { wrong: 'Is it spicy? I am exited!', right: "Is it spicy? I'm excited!", why: '"Exited" significa "salió". "Excited" es emocionado. ¡Y ojo con "embarrassed", que es avergonzado, no embarazada!' },
      ],
      pronunciation: {
        focus: 'Palabras de comida que se pronuncian distinto',
        tip: 'Muchas palabras de restaurante se escriben parecido al español pero suenan muy distinto. Escúchalas y repite fijándote en la sílaba fuerte.',
        words: [
          { word: 'vegetables', sounds: '/ˈvedʒtəblz/ — "VECH-ta-buls" (3 sílabas)', es: 'verduras' },
          { word: 'chocolate', sounds: '/ˈtʃɑːklət/ — "CHAK-let"', es: 'chocolate' },
          { word: 'salmon', sounds: '/ˈsæmən/ — "SA-mon" (la L no suena)', es: 'salmón' },
          { word: 'steak', sounds: '/steɪk/ — "steik"', es: 'filete de res' },
          { word: 'dessert', sounds: '/dɪˈzɜːrt/ — "di-ZERT"', es: 'postre' },
          { word: 'water', sounds: '/ˈwɑːtər/ — "UA-der"', es: 'agua' },
        ],
      },
      reading: {
        title: 'Dinner at a diner',
        paragraphs: [
          'Andrés and his girlfriend Natalia are in Orlando. Tonight they have dinner at a typical American diner. The waitress gives them two menus and says: "Hi guys! Can I get you something to drink?"',
          "Andrés orders a lemonade and Natalia orders water. For the main course, Andrés has a cheeseburger with fries. Natalia is vegetarian, so she asks: \"Do you have any vegetarian options?\" The waitress recommends a veggie burger.",
          "The food is delicious and the portions are huge! They can't finish it, so they ask for a box to take it home. The check is forty-two dollars. Andrés leaves an eight-dollar tip.",
        ],
        glossary: [
          { en: 'diner', es: 'restaurante típico americano' },
          { en: 'waitress', es: 'mesera' },
          { en: 'huge', es: 'enorme' },
          { en: 'box', es: 'caja (para llevar)' },
        ],
        questions: [
          { q: 'What does Natalia drink?', options: ['Lemonade', 'Water', 'Soda'], answer: 1 },
          { q: 'Why does Natalia ask for vegetarian options?', options: ["She doesn't like burgers", "She's vegetarian", "She's allergic to cheese"], answer: 1 },
          { q: 'Why do they ask for a box?', options: ['The portions are very big', "The food isn't good", 'They are late'], answer: 0 },
          { q: 'How much is the tip?', options: ['$42', '$8', '$4'], answer: 1, explanation: 'Unos $8 sobre $42 es cerca del 19 %, una propina normal en EE. UU.' },
        ],
      },
      culture: {
        title: 'Propina, refill y "doggy bag"',
        body: 'En EE. UU. los meseros ganan buena parte de su sueldo con propinas, por eso se deja entre 15 y 20 % (o más si el servicio es excelente). En muchos restaurantes las gaseosas tienen "free refills": te las rellenan gratis. Y pedir una caja para llevar lo que sobra es totalmente normal: "Can I get a box for this?"',
      },
      mission: {
        title: 'Ordena tu comida favorita',
        task: 'Imagina que estás en un restaurante en Nueva York. Escribe y luego di en voz alta todo el pedido: bebida, entrada, plato fuerte con un cambio especial y la cuenta.',
        steps: ['Saluda y pide la bebida', 'Pide la comida con "I\'ll have…"', 'Haz una petición especial (sin cebolla, alergia…)', 'Pide la cuenta con cortesía'],
        model: "Hi! Can I have a lemonade, please? For the starter, I'd like the tomato soup. And I'll have the chicken with rice, but no onions, please. I'm allergic. … Excuse me, could we get the check, please?",
      },
      exercises: [
        { type: 'fix', sentence: 'Give me the menu.', answers: ['Can I have the menu, please?', 'Could I have the menu, please?', 'Could we have the menu, please?', 'Can we have the menu, please?'], explanation: 'Pide con "Can I have…, please?".' },
        { type: 'dictation', audio: "I'd like a coffee, please.", translation: 'Quisiera un café, por favor.' },
        { type: 'choice', prompt: 'Quieres tu café para llevar. ¿Qué dices?', options: ['A coffee for carry.', 'A coffee to go, please.', 'A coffee for take.'], answer: 1 },
        { type: 'listen', audio: "I'm allergic to peanuts.", options: ['Soy alérgico al maní.', 'Me encanta el maní.', 'No tengo maní.'], answer: 0 },
        { type: 'fix', sentence: 'I am very exited to try the food.', answers: ['I am very excited to try the food.', "I'm very excited to try the food."], explanation: 'Emocionado = excited.' },
        { type: 'match', prompt: 'Une el menú', pairs: [['starter', 'entrada'], ['main course', 'plato fuerte'], ['dessert', 'postre'], ['check', 'cuenta'], ['tip', 'propina']] },
        { type: 'dictation', audio: 'Could we get the check, please?', translation: '¿Nos trae la cuenta, por favor?' },
        { type: 'fill', sentence: "I'll ___ the salmon, please.", answers: ['have'], hint: 'forma típica de ordenar' },
        { type: 'order', words: ['Do', 'you', 'have', 'any', 'vegetarian', 'options?'], translation: '¿Tienen opciones vegetarianas?' },
        { type: 'truefalse', statement: 'En EE. UU. pedir una caja para llevarte lo que sobró es mal visto.', answer: false, explanation: 'Es completamente normal.' },
      ],
    },
  ],
  // ─── Módulo 3: Salir al mundo ───────────────────────────────────────────
  [
    // M3L1 · Direcciones
    {
      vocabulary: [
        { en: 'Traffic light', es: 'Semáforo', example: 'Turn right at the traffic light.', emoji: '🚦' },
        { en: 'Crosswalk', es: 'Paso de cebra', example: 'Cross at the crosswalk.', emoji: '🚸' },
        { en: 'Between', es: 'Entre', example: 'The bank is between the café and the pharmacy.', emoji: '↔️' },
        { en: 'Behind', es: 'Detrás de', example: 'The parking lot is behind the mall.', emoji: '🔙' },
        { en: 'Subway station', es: 'Estación de metro', example: 'Where is the nearest subway station?', emoji: '🚇' },
        { en: 'Lost', es: 'Perdido', example: "Excuse me, I'm lost.", emoji: '🗺️' },
      ],
      mistakes: [
        { wrong: 'Where is the museum? (sin saludar, a un desconocido)', right: 'Excuse me, where is the museum, please?', why: 'Siempre empieza con "Excuse me" para llamar la atención de un desconocido. Sin eso suena brusco.' },
        { wrong: 'Is near of the park.', right: "It's near the park.", why: '"Near" no lleva "of". Y en inglés siempre necesitas sujeto: "It\'s", no solo "Is".' },
        { wrong: 'Go straight two blocks and turn to the left in the corner.', right: 'Go straight for two blocks and turn left at the corner.', why: 'Se dice "turn left/right" sin "to the" y "at the corner" (no "in").' },
        { wrong: 'In front of (para decir "al frente, cruzando la calle")', right: 'Across from / Opposite', why: '"In front of" es delante de algo (pegado). Si está cruzando la calle, se dice "across from".' },
      ],
      pronunciation: {
        focus: 'La "r" inglesa en right, straight y corner',
        tip: 'La R inglesa no vibra como la nuestra. Enrolla la lengua hacia atrás sin tocar el paladar. "Right" empieza casi como una "u" muy corta: /uráit/. Y en "corner" la R final apenas se siente.',
        words: [
          { word: 'right', sounds: '/raɪt/ — "(u)RAIT"', es: 'derecha' },
          { word: 'straight', sounds: '/streɪt/ — "STREIT"', es: 'derecho' },
          { word: 'corner', sounds: '/ˈkɔːrnər/ — "KOR-ner"', es: 'esquina' },
          { word: 'street', sounds: '/striːt/ — "STRIIT" (sin "e" al inicio)', es: 'calle' },
          { word: 'library', sounds: '/ˈlaɪbreri/ — "LAI-bre-ri"', es: 'biblioteca' },
        ],
      },
      reading: {
        title: 'A message from a friend',
        paragraphs: [
          "Hi Camilo! Welcome to London! Here are the directions to my apartment from the station. When you leave Camden Town station, turn left. Walk straight for two blocks. You'll see a big supermarket on the corner.",
          "Turn right at the supermarket. My building is the third on the left. It's blue and it's between a small café and a bookstore. Across from my building there's a park.",
          "My apartment is on the fourth floor, number 4B. Text me when you arrive and I'll come down. It's a ten-minute walk. Don't take a taxi, it's very expensive here! See you soon, Emma.",
        ],
        glossary: [
          { en: 'leave', es: 'salir de' },
          { en: 'building', es: 'edificio' },
          { en: 'floor', es: 'piso' },
          { en: 'text me', es: 'escríbeme (mensaje)' },
        ],
        questions: [
          { q: 'What does Camilo do first when he leaves the station?', options: ['Turn right', 'Turn left', 'Take a taxi'], answer: 1 },
          { q: "Where is Emma's building?", options: ['Next to the station', 'Between a café and a bookstore', 'Behind the supermarket'], answer: 1 },
          { q: "What's across from her building?", options: ['A park', 'A supermarket', 'A café'], answer: 0 },
          { q: 'Why does Emma say not to take a taxi?', options: ["It's far", "It's expensive", "It's dangerous"], answer: 1 },
        ],
      },
      culture: {
        title: 'Blocks en EE. UU., landmarks en Reino Unido',
        body: 'En ciudades de EE. UU. con calles en cuadrícula (como Nueva York) la gente da direcciones en cuadras: "Go two blocks and turn left". En Reino Unido las calles son irregulares, así que se usan puntos de referencia: "Turn left at the pub". Y si alguien te dice "It\'s just around the corner", está muy cerca.',
      },
      mission: {
        title: 'Guía a un turista',
        task: 'Escoge un lugar real cerca de tu casa (una panadería, un parque, una estación). Da las instrucciones en inglés para llegar desde tu puerta, como si un turista te preguntara.',
        steps: ['Empieza con "Sure! Go…"', 'Usa al menos dos instrucciones (turn, go straight)', 'Describe la ubicación final (next to, across from)', 'Di si está cerca o lejos'],
        model: "Sure! Go out of the building and turn right. Go straight for three blocks. At the traffic light, turn left. The bakery is on the corner, next to the pharmacy. It's very near, about five minutes.",
      },
      exercises: [
        { type: 'dictation', audio: 'Turn left at the corner.', translation: 'Gira a la izquierda en la esquina.' },
        { type: 'fix', sentence: 'The bank is near of the hotel.', answers: ['The bank is near the hotel.'], explanation: '"Near" va sin "of".' },
        { type: 'choice', prompt: 'La farmacia está cruzando la calle desde el hotel. ¿Cómo lo dices?', options: ["It's in front of the hotel.", "It's across from the hotel.", "It's behind the hotel."], answer: 1 },
        { type: 'listen', audio: "It's between the bank and the café.", options: ['Está detrás del banco.', 'Está entre el banco y el café.', 'Está al lado del café.'], answer: 1 },
        { type: 'fix', sentence: 'Turn to the right in the traffic light.', answers: ['Turn right at the traffic light.'], explanation: '"Turn right" sin "to the" y "at the traffic light".' },
        { type: 'match', prompt: 'Une las preposiciones', pairs: [['next to', 'al lado de'], ['behind', 'detrás de'], ['between', 'entre'], ['across from', 'al frente (cruzando)']] },
        { type: 'dictation', audio: "Excuse me, I'm lost.", translation: 'Disculpe, estoy perdido.' },
        { type: 'fill', sentence: 'Go ___ for two blocks.', answers: ['straight'], hint: 'derecho' },
        { type: 'order', words: ['Where', 'is', 'the', 'nearest', 'subway', 'station?'], translation: '¿Dónde está la estación de metro más cercana?' },
        { type: 'truefalse', statement: 'El apartamento de Emma está en el cuarto piso.', answer: true },
      ],
    },
    // M3L2 · Aeropuerto
    {
      vocabulary: [
        { en: 'Check in', es: 'Hacer el registro', example: 'You can check in online.', emoji: '🧾' },
        { en: 'Window seat', es: 'Silla de ventana', example: 'Can I have a window seat?', emoji: '🪟' },
        { en: 'Departure', es: 'Salida', example: 'The departure is at 10:40.', emoji: '🛫' },
        { en: 'Arrival', es: 'Llegada', example: 'Arrivals are on the first floor.', emoji: '🛬' },
        { en: 'Baggage claim', es: 'Recogida de equipaje', example: 'Where is baggage claim?', emoji: '🧳' },
        { en: 'Customs', es: 'Aduana', example: 'Do I need to go through customs?', emoji: '🛃' },
        { en: 'Layover', es: 'Escala', example: 'I have a three-hour layover in Panama.', emoji: '⏳' },
      ],
      mistakes: [
        { wrong: 'I come for tourism. / I come to visit.', right: "I'm here on vacation. / I'm here for tourism.", why: 'En migración responde con "I\'m here…" y frases cortas y claras.' },
        { wrong: 'I stay two weeks.', right: "I'm staying for two weeks.", why: 'Para planes ya decididos se usa el presente continuo: "I\'m staying", "I\'m leaving on Monday".' },
        { wrong: 'My flight is delay.', right: 'My flight is delayed.', why: '"Delayed" es un adjetivo terminado en -ed. "Delay" es el sustantivo: "There\'s a delay".' },
        { wrong: 'Where I can find my luggage?', right: 'Where can I find my luggage?', why: 'En las preguntas, el auxiliar (can, do, is) va antes del sujeto.' },
      ],
      pronunciation: {
        focus: 'Palabras clave del aeropuerto',
        tip: 'En los altavoces del aeropuerto hablan rápido. Entrena el oído con estas palabras, sobre todo "gate" (que no suena "gat" sino "geit") y "boarding" (con la R suave).',
        words: [
          { word: 'gate', sounds: '/geɪt/ — "GUEIT"', es: 'puerta de embarque' },
          { word: 'boarding', sounds: '/ˈbɔːrdɪŋ/ — "BOR-ding"', es: 'abordaje' },
          { word: 'luggage', sounds: '/ˈlʌɡɪdʒ/ — "LA-guich"', es: 'equipaje' },
          { word: 'aisle', sounds: '/aɪl/ — "AIL" (la S no suena)', es: 'pasillo' },
          { word: 'customs', sounds: '/ˈkʌstəmz/ — "KAS-tems"', es: 'aduana' },
        ],
      },
      reading: {
        title: 'Announcements at JFK',
        paragraphs: [
          '"Good afternoon, ladies and gentlemen. This is the final boarding call for Avianca flight two four five to Bogotá. All passengers please go to gate B twelve immediately."',
          '"Attention, passengers on American Airlines flight nine zero one to Miami. Your flight is delayed by forty-five minutes. The new departure time is six fifteen p.m. We apologize for the inconvenience."',
          '"Passengers arriving from international flights, please have your passport and customs form ready. Remember: do not leave your bags unattended. Unattended bags will be removed."',
        ],
        glossary: [
          { en: 'final call', es: 'última llamada' },
          { en: 'immediately', es: 'inmediatamente' },
          { en: 'we apologize', es: 'pedimos disculpas' },
          { en: 'unattended', es: 'sin vigilancia' },
        ],
        questions: [
          { q: 'Which gate is the flight to Bogotá?', options: ['B2', 'B12', 'B20'], answer: 1 },
          { q: 'How long is the delay of the Miami flight?', options: ['15 minutes', '45 minutes', '6 hours'], answer: 1 },
          { q: 'What is the new departure time to Miami?', options: ['6:15 p.m.', '6:50 p.m.', '9:01 p.m.'], answer: 0 },
          { q: 'What happens to unattended bags?', options: ['They go to baggage claim', 'They are removed', 'They go on the next flight'], answer: 1 },
        ],
      },
      culture: {
        title: 'Cómo es la entrevista de migración en EE. UU.',
        body: 'El oficial (CBP officer) hará 3-5 preguntas rápidas: el propósito del viaje, cuánto tiempo te quedas, dónde te vas a hospedar y a qué te dedicas. Responde corto, con calma y con la verdad. Ten a mano la dirección del hotel y el tiquete de regreso. No hagas chistes sobre bombas o drogas: lo toman en serio.',
      },
      mission: {
        title: 'Supera la entrevista de migración',
        task: 'Responde en voz alta estas 5 preguntas como si estuvieras frente al oficial. Grábate y revisa que suenes claro y seguro.',
        steps: ['What is the purpose of your visit?', 'How long are you staying?', 'Where are you staying?', 'What do you do?', 'Do you have anything to declare?'],
        model: "I'm here on vacation. I'm staying for ten days. I'm staying at the Hilton hotel in Orlando. I'm a software developer. No, I don't have anything to declare.",
      },
      exercises: [
        { type: 'dictation', audio: "I'm here on vacation.", translation: 'Estoy aquí de vacaciones.' },
        { type: 'fix', sentence: 'My flight is delay.', answers: ['My flight is delayed.'], explanation: 'Retrasado = delayed.' },
        { type: 'listen', audio: 'Please go to gate C nine.', options: ['Vaya a la puerta C9.', 'Vaya a la puerta C19.', 'Vaya a la puerta G9.'], answer: 0 },
        { type: 'choice', prompt: 'El oficial pregunta "How long are you staying?". ¿Qué respondes?', options: ['At the Marriott.', 'For two weeks.', 'On vacation.'], answer: 1 },
        { type: 'fix', sentence: 'Where I can find baggage claim?', answers: ['Where can I find baggage claim?', 'Where can I find the baggage claim?'], explanation: 'En preguntas: can + sujeto.' },
        { type: 'match', prompt: 'Une las palabras', pairs: [['layover', 'escala'], ['customs', 'aduana'], ['departure', 'salida'], ['arrival', 'llegada'], ['window seat', 'silla de ventana']] },
        { type: 'dictation', audio: 'Can I have an aisle seat?', translation: '¿Me puede dar una silla de pasillo?' },
        { type: 'fill', sentence: "I'm ___ at a hotel in Miami.", answers: ['staying'], hint: 'quedarse, presente continuo' },
        { type: 'order', words: ['I', 'have', 'a', 'layover', 'in', 'Panama'], translation: 'Tengo una escala en Panamá.' },
        { type: 'truefalse', statement: 'En el anuncio, el vuelo a Bogotá está retrasado.', answer: false, explanation: 'Es la última llamada de abordaje; el retrasado es el de Miami.' },
      ],
    },
    // M3L3 · Primera conversación completa
    {
      vocabulary: [
        { en: 'What about you?', es: '¿Y tú?', example: "I love salsa. What about you?", emoji: '🔄' },
        { en: 'Really?', es: '¿En serio?', example: 'Really? That\'s amazing!', emoji: '😮' },
        { en: 'That sounds fun', es: 'Suena divertido', example: 'A trip to the beach? That sounds fun!', emoji: '🎈' },
        { en: 'Nice talking to you', es: 'Un gusto hablar contigo', example: 'Well, nice talking to you!', emoji: '👋' },
        { en: 'Keep in touch', es: 'Seguir en contacto', example: "Let's keep in touch!", emoji: '📲' },
        { en: 'Free time', es: 'Tiempo libre', example: 'What do you do in your free time?', emoji: '🕒' },
      ],
      mistakes: [
        { wrong: 'What do you do? — I am doing my homework.', right: "What do you do? — I'm an accountant.", why: '"What do you do?" pregunta por tu trabajo o profesión, no por lo que estás haciendo ahora.' },
        { wrong: 'Yes. / No. (y te quedas callado)', right: 'Yes, I love it! What about you?', why: 'Responder con una sola palabra mata la conversación. Agrega un detalle y devuelve la pregunta.' },
        { wrong: 'I like very much the music.', right: 'I really like music. / I like music a lot.', why: '"Very much" va al final o se reemplaza por "really". Y para gustos generales no se usa "the".' },
        { wrong: 'Is very interesting!', right: "It's very interesting!", why: 'El inglés nunca omite el sujeto. Siempre "It\'s", "She\'s", "They\'re"…' },
      ],
      pronunciation: {
        focus: 'Entonación de preguntas',
        tip: 'Las preguntas de sí/no suben al final ("Do you like it? ↗"). Las preguntas con What, Where, How bajan al final ("Where are you from? ↘"). Si las haces todas subiendo, sonarás inseguro.',
        words: [
          { word: 'Do you like it?', sounds: 'sube ↗ al final', es: '¿Te gusta?' },
          { word: 'Where are you from?', sounds: 'baja ↘ al final', es: '¿De dónde eres?' },
          { word: 'Are you a student?', sounds: 'sube ↗ al final', es: '¿Eres estudiante?' },
          { word: 'What do you do?', sounds: 'baja ↘ al final', es: '¿A qué te dedicas?' },
        ],
      },
      reading: {
        title: 'Chatting on a language exchange app',
        paragraphs: [
          "Kate: Hi! I'm Kate. I'm from Chicago. I'm learning Spanish. Nice to meet you! 😊",
          "Juan: Hi Kate! Nice to meet you too. I'm Juan, from Manizales, Colombia. I'm learning English. What do you do?",
          "Kate: I'm a graphic designer. I work from home. And you? Juan: I'm a coffee farmer! My family has a small farm. Kate: Really? That's so cool! I love Colombian coffee. Juan: Haha, thank you! What do you do in your free time? Kate: I play the guitar and I go hiking. Juan: That sounds fun. I like hiking too. Let's keep in touch! We can talk on Saturday.",
        ],
        glossary: [
          { en: 'graphic designer', es: 'diseñador(a) gráfico(a)' },
          { en: 'farmer', es: 'agricultor, caficultor' },
          { en: 'farm', es: 'finca' },
          { en: 'go hiking', es: 'hacer senderismo' },
        ],
        questions: [
          { q: 'Why is Kate on the app?', options: ['To learn Spanish', 'To buy coffee', 'To find a job'], answer: 0 },
          { q: "What's Juan's job?", options: ['Graphic designer', 'Coffee farmer', 'Guitar teacher'], answer: 1 },
          { q: 'What do Kate and Juan both like?', options: ['Playing the guitar', 'Hiking', 'Working from home'], answer: 1 },
          { q: 'When can they talk again?', options: ['On Sunday', 'Tomorrow', 'On Saturday'], answer: 2 },
        ],
      },
      culture: {
        title: 'Temas seguros y temas que mejor evitar',
        body: 'Al conocer a alguien, los temas seguros son: trabajo o estudios, de dónde eres, hobbies, viajes, comida, series y el clima. Evita preguntar el salario, la edad, la religión, la política o el peso. Y un consejo: a los extranjeros les encanta hablar de Colombia; prepara 2-3 frases sobre tu ciudad.',
      },
      mission: {
        title: 'Conversación completa con IA o con un amigo',
        task: 'Ten una conversación de 3 minutos en inglés (con un amigo, un compañero o un asistente de IA por voz). Usa la estructura: saludo, 4 preguntas, reacciones y despedida.',
        steps: ['Pregunta nombre, origen, trabajo y hobbies', 'Reacciona con "Really?" o "That sounds fun"', 'Devuelve preguntas con "What about you?"', 'Cierra con "Nice talking to you"'],
        model: "Hi, I'm Sergio. Where are you from? — I'm from Texas. — Really? Cool! What do you do? — I'm a nurse. What about you? — I'm a lawyer. What do you do in your free time? — I play soccer. — That sounds fun! Well, nice talking to you. Let's keep in touch!",
      },
      exercises: [
        { type: 'choice', prompt: 'Alguien te pregunta "What do you do?". ¿Qué responde?', options: ["I'm watching TV.", "I'm a teacher.", 'I do fine.'], answer: 1 },
        { type: 'dictation', audio: 'What do you do in your free time?', translation: '¿Qué haces en tu tiempo libre?' },
        { type: 'fix', sentence: 'Is very interesting!', answers: ["It's very interesting!", 'It is very interesting!'], explanation: 'Siempre con sujeto.' },
        { type: 'listen', audio: 'That sounds fun!', options: ['¡Suena divertido!', '¡Es muy ruidoso!', '¡Qué miedo!'], answer: 0 },
        { type: 'fix', sentence: 'I like very much the coffee.', answers: ['I really like coffee.', 'I like coffee very much.', 'I like coffee a lot.'], explanation: '"Very much" al final o "really" antes del verbo.' },
        { type: 'choice', prompt: '¿Cuál es la mejor respuesta para que la conversación siga?', options: ['Yes.', 'Yes, I love it! What about you?', 'Yes, OK.'], answer: 1 },
        { type: 'dictation', audio: 'Nice talking to you!', translation: '¡Un gusto hablar contigo!' },
        { type: 'match', prompt: 'Une la reacción', pairs: [['Really?', '¿En serio?'], ['Me too.', 'Yo también.'], ['Keep in touch!', '¡Sigamos en contacto!'], ['What about you?', '¿Y tú?']] },
        { type: 'order', words: ['What', 'do', 'you', 'do', 'on', 'weekends?'], translation: '¿Qué haces los fines de semana?' },
        { type: 'truefalse', statement: 'Es buena idea preguntarle el salario a alguien que acabas de conocer.', answer: false, explanation: 'El salario es un tema privado en la cultura anglosajona.' },
      ],
    },
  ],
];
